### PR TITLE
Added Q_SPY support for Arduino qpcpp_arm-cm

### PR DESCRIPTION
**Pull request by vChavezB**
I have been testing the QP-Cpp framework for Arduino and I wanted to test Q_SPY. After searching the SourceForge forum I found out that there is no support and that the AVR version cant use it since its based on QP-Nano.

Since I have a spare Arduino Due I have started to port the `QP::QS` platform-specific functions. I did not find a lot of documentation on how to do the port, so I just searched the cortex-m examples to make sense of what the Q_SPY hardware-specific API does.

The port works and is rather simple but took me a while to understand how to put everything together. 

## Changes 

- Added the QS source files from the [QP-cpp repo](https://github.com/QuantumLeaps/qpcpp/tree/8803d8faed8124deb91073e4cf8603fd9e0b07ba).
  -  Added conditional compilation based on the  `Q_SPY` define. This is due to the limitations of the Arduino IDE which does not have an option to select which files to compile and is not compatible with other build systems.
- Added a new Blinky example that uses QSPY based on Blinky-sam. 
- Added QS BSP for Arduino SDK `libraries/qpcpp_arm-cm/src/qs_bsp.cpp`

## Tested

- Object, sig, function  dictionary
- Use of Reset command
- Global filters

## Caveats

This pull request won't compile out of the box. Due to limitations of the Arduino platform, compiler definition flags -D cant be added in the project (so-called sketch). The port requires the Q_SPY definition. At the moment it can be added through the platforms.txt file or adding a new Board definition which includes `MyBoard.build.extra_flags= -DQ_SPY`

## Sequential chart results

```
qspy.exe -c COM54 -b 115200 -g ?,Blinky::instance

           +-------+-------+   +-------+-------+
           |       ?       |   |Blinky::instanc|
           +-------+-------+   +-------+-------+
0000000497         *--TIMEOUT_SIG----->|
0000000497         /              <Blinky::on>
0000000992         *--TIMEOUT_SIG----->|
0000000992         /             <Blinky::off>
0000001487         *--TIMEOUT_SIG----->|
0000001487         /              <Blinky::on>
0000001983         *--TIMEOUT_SIG----->|
0000001983         /             <Blinky::off>
0000002478         *--TIMEOUT_SIG----->|
0000002478         /              <Blinky::on>
0000002973         *--TIMEOUT_SIG----->|
0000002973         /             <Blinky::off>
```

## Final comments

My intention to bring support to the Arduino SDK is to use QPCPP with students that are familiar with the Arduino IDE. Now they can debug their program with the help of QSpy. Also I want to use it for other projects we have here related to protocol stacks, where this might come in handy.

### CODE REVIEW

**Comment by quantum-leaps** [comment]
I'm not sure how to test your pull request.

In my naive attempt, I simply downloaded your code and I have built the `blinky-sam-qspy.ino` with the Arduino IDE. The build actually succeeded, but no Spy output was produced.

How and where do I define the `Q_SPY` macro?

--MMS

**Comment by vChavezB** [comment]
Hello Miro,

The Arduino IDE does not have a straightforward way to add definitions via `-D` to the compiler. There are two options that I know of

### Platforms.txt file

You can hardcode the extra flag in your Arduino board packages directory. For windows that is 

`C:\Users\USERNAME\AppData\Local\Arduino15\packages\arduino\hardware\sam\YOUR_VERSION\platform.txt`

In this file you need to locate the line that starts with `compiler.cpp.flags` and add the macro `-DQ_SPY`
```
compiler.cpp.flags=-c -g -Os {compiler.warning_flags} -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -MMD -DQ_SPY
```

The disadvantage is that all your Arduino Due projects with the Arduino IDE will now be compiled with the Q_SPY MACRO.


### Boards.txt 

You can add a new Boards definition to the end of the Boards.txt file

`C:\Users\USERNAME\AppData\Local\Arduino15\packages\arduino\hardware\sam\YOUR_VERSION\boards.txt`

The difference is that you can select the board and only while using this new board the Q_SPY macro will be set in the compiler flags. Here's an example

```
arduino_due_x_dbg_qspy.name=Arduino Due (Programming Port) QSPY
arduino_due_x_dbg_qspy.vid.0=0x2341
arduino_due_x_dbg_qspy.pid.0=0x003d
arduino_due_x_dbg_qspy.vid.1=0x2A03
arduino_due_x_dbg_qspy.pid.1=0x003d
arduino_due_x_dbg_qspy.upload.tool=bossac
arduino_due_x_dbg_qspy.upload.protocol=sam-ba
arduino_due_x_dbg_qspy.upload.maximum_size=524288
arduino_due_x_dbg_qspy.upload.use_1200bps_touch=true
arduino_due_x_dbg_qspy.upload.wait_for_upload_port=false
arduino_due_x_dbg_qspy.upload.native_usb=false
arduino_due_x_dbg_qspy.build.mcu=cortex-m3
arduino_due_x_dbg_qspy.build.f_cpu=84000000L
arduino_due_x_dbg_qspy.build.usb_manufacturer="Arduino LLC"
arduino_due_x_dbg_qspy.build.usb_product="Arduino Due"
arduino_due_x_dbg_qspy.build.board=SAM_DUE
arduino_due_x_dbg_qspy.build.core=arduino
arduino_due_x_dbg_qspy.build.extra_flags=-D__SAM3X8E__ -mthumb {build.usb_flags} -DQ_SPY
arduino_due_x_dbg_qspy.build.ldscript=linker_scripts/gcc/flash.ld
arduino_due_x_dbg_qspy.build.variant=arduino_due_x
arduino_due_x_dbg_qspy.build.variant_system_lib=libsam_sam3x8e_gcc_rel.a
arduino_due_x_dbg_qspy.build.vid=0x2341
arduino_due_x_dbg_qspy.build.pid=0x003e
```

Regards

**Comment by quantum-leaps** [comment]
Yeah, it seems that Arduino forbids providing external macros, because the Arduino build process simply cannot reliably handle the potentially cascaded dependencies in the included libraries it may cause.

Both ways in working around the Arduino limitations (`platform.txt` and `boards.txt`) are quite complex and go against the main premise of Arduino, which is to make it **simple**, even for non-programmers. 

Perhaps a better way to go would be to permanently enable Q_SPY in the qpcpp library for Arduino, so that the library code will be always instrumented with Q_SPY. Of course, this would make the library bigger and slower, but with all "global filters" closed, the overhead should be manageable when Q_SPY is not actually used. This would be the default.

In case someone would like to use Q_SPY, they would need to provide some reasonable TX/RX buffers and then they would need to perform the QS output/input from the idle callback. All this would be decided at run-time, as opposed to compile-time (because Arduino cannot handle the compile-time configuration).

--MMS

**Comment by vChavezB** [comment]
> quite complex and go against the main premise of Arduino, 

Yes, that is true. There have been feature requests for Arduino to include extra flags for the library.properties file or in the IDE but it hasn't been implemented.

>Perhaps a better way to go would be to permanently enable Q_SPY in the qpcpp library for Arduino

What about a header file that is included by all the source files where the Q_SPY macro can be enabled/disabled. Then the only modification to the source files would be adding a new include directive + a header file

```
#include "qs_arduino.h"
#ifdef Q_SPY                // QS software tracing enabled?
    #include "qs_port.hpp"  // QS port
    #include "qs_pkg.hpp"   // QS facilities for pre-defined trace records
#else
    #include "qs_dummy.hpp" // disable the QS software tracing
#endif // Q_SPY
/*
* REST OF THE SOURC FILE
* /
```

**Comment by quantum-leaps** [comment]
Please check out the new [qp-arduino release 6.9.4](https://github.com/QuantumLeaps/qp-arduino/releases). This release supports QP/Spy. Please read Section "QP/Spy Software Tracing Support" in README.md.

--MMS

**Comment by vChavezB** [comment]
Thanks.for.the update! As from my other issue I posted on the QP CPP repository,  I am working on an IO Link stack. I was using my forked QP arduino repo and the application stopped after some seconds when I enabled Q SPY

I changed the Arduino bundled compiler from GCC 4.8.3 to the latest ARM toolchain 10.3-2021.10 and.now it works. So I am not sure what the problem was. I will try again with the default GCC version from Arduino and the changes you made.

**Comment by vChavezB** [comment]
I tested the new release and the problem is still the same. The application stop working after 2 seconds.  QSpy works with the simple blinky example with GCC v4.8.3 as I already tested from the first post of this pull request. But with my other project which is more complex and has 6 active objects it doesn't. Also, the project uses the peripheral interrupts of the MCU such as USART, Timers and GPIO.

I won't go too deep into the issue since it works by just updating the compiler.

Just as a side note why didn't you put the BSP-specific QS API:
- `QP::QS::onReset`
- `QP::QS::onFlush`
- `QP::QS::onGetTime`

  in a separate source file that could be inside the library (as in this pull request)? 

These functions won't change (unless the Arduino SDK changes) and the end-user will have to copy-paste them each time they create a new sketch.  The only function that might change is `onReset `, as there isn't an Arduino API for resetting the board. For this unique case, you could conditionally compile the `onReset ` for the target. For example for the Arduino Due, the IDE passes automatically the macro `-DARDUINO_SAM_DUE`. 

Kind regards,
Victor

**Comment by quantum-leaps** [comment]
> The application stop working after 2 seconds... Also, the project uses the peripheral interrupts of the MCU such as USART, Timers and GPIO.

To troubleshoot the problem, I'd obviously need some more information as to how the system fails. The current version (i.e. qp-arduino 6.9.4) worked with the DPP example (6 active objects) without hiccups. A good starting point is to be able to reproduce the problem. Would it be possible to get a simple software that demonstrates the failure?

> Just as a side note why didn't you put the BSP-specific QS API...

The main objective of this design was to strictly encapsulate all QS-related code entirely in the `bsp.cpp` file. For example, the decision to use or not to use QS at all. I specifically didn't want any macros to "leak" to the library code. I don't trust the Arduino build process to always handle such cascaded dependencies correctly. I've been burnt with "broken" builds before.

But to be clear, that design decision is independent from the problems that you see in your application. So, let's just try to fix the existing problems. I hope this makes sense to you.

--MMS

**Comment by vChavezB** [comment]
>Would it be possible to get a simple software that demonstrates the failure?

Well, I just debugged the code and found out it was a mistake on my part. I forgot to return `Q_RET_HANDLED` in one of my states which made QP hang in a loop. What I find odd is that using the latest bundled compiler in the ARM toolchain automagically hid this error.

> I don't trust the Arduino build process to always handle such cascaded dependencies correctly

I see your point. Ok, then I think this pull request can be closed as QSpy is now working with Arduino. I will probably test QP and QS with a Raspberry Pi Pico to check if it works as well.

**Comment by quantum-leaps** [comment]
> ...  I forgot to return Q_RET_HANDLED in one of my states ...

This whole class of silly coding mistakes can be entirely avoided by using automatic code generation. That's why all examples qp-arduino contain QM models. But I guess developing trust in code generation takes some time and a bunch of totally avoidable mistakes to finally get acceptance.

--MMS

**Pull request closed without merging**
